version: "3.8"

services:
  app:
    build: .
    environment:
      - PORT=8080
      - BOOK_SERVICE_URI=localhost:50052
      - USER_SERVICE_URI=localhost:50051
      - JWT_SECRET=SECRETP3W2
    ports:
      - "8080:8080"
