services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2

  app:
    build:
      context: ./client
    ports:
      - "8080:8080"

  app1:
    build:
      context: ./server
    ports:
      - "50051:50051"

  app2:
    build:
      context: ./server2
    ports:
      - "50052:50052"
