basePath: /
definitions:
  model.BookTransaction:
    properties:
      bookID:
        type: string
      userID:
        type: string
    type: object
  model.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.RegisterUser:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple library API
  title: Library API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Get all books
      parameters:
      - description: Book status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get all books
      tags:
      - books
  /books/borrow:
    post:
      consumes:
      - application/json
      description: Borrow a book
      parameters:
      - description: Book transaction details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.BookTransaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Borrow a book
      tags:
      - books
  /books/return:
    post:
      consumes:
      - application/json
      description: Return a book
      parameters:
      - description: User ID and Book ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.BookTransaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Return a book
      tags:
      - books
  /books/update-status:
    get:
      consumes:
      - application/json
      description: Update book status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update book status
      tags:
      - books
  /users/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - User
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the role 'User'
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - User
swagger: "2.0"
